# template.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-job-python
            image: cron-job-python
            volumeMounts:
            - name: code
              mountPath: /opt/app-root/src
          restartPolicy: OnFailure
          volumes:
          - name: code
            gitRepo:
              repository: https://github.com/torvicvasil1993/cron-job-python
              revision: main



